name: api-sandbox

services:
  ven:
    image: fpedgeplatformsflab.azurecr.io/api-sandbox/ven:latest
    ports:
      - 8000:8000
    volumes:
      - ${LOG_FOLDER}:/plaid/logs
    networks:
      - api-sandbox
    depends_on:
      - middleware
    command: ["--oadr.vtnUrl=${VTN_URL}"]
  middleware:
    image: fortress_ven_middleware:0.0.1
    networks:
      - api-sandbox

networks:
  api-sandbox:
    external: true